In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
### scikit learn --> import sklearn

In [3]:
# pip install scikit-learn

In [4]:
# pip install --upgrade pip

In [5]:
df = pd.read_csv('International_Education_Costs.csv')

df.head()

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
0,USA,Cambridge,Harvard University,Computer Science,Master,2.0,55400,83.5,2200,160,1500,1.00
1,UK,London,Imperial College London,Data Science,Master,1.0,41200,75.8,1800,485,800,0.79
2,Canada,Toronto,University of Toronto,Business Analytics,Master,2.0,38500,72.5,1600,235,900,1.35
3,Australia,Melbourne,University of Melbourne,Engineering,Master,2.0,42000,71.2,1400,450,650,1.52
4,Germany,Munich,Technical University of Munich,Mechanical Engineering,Master,2.0,500,70.5,1100,75,550,0.92

In [6]:
55400*86

4764400

In [7]:
df.tail()

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
902,France,Strasbourg,University of Strasbourg,Data Analytics,Master,2.0,4000,70.2,1000,99,850,0.92
903,Malaysia,Nilai,USIM,Computer Science,Bachelor,3.0,6800,50.5,400,120,400,4.65
904,Saudi Arabia,Al-Ahsa,King Faisal University,Information Systems,Master,2.0,4200,64.2,600,200,800,3.75
905,USA,Seattle,University of Washington,Software Development,PhD,5.0,50000,77.8,2000,160,1500,1.00
906,UK,Nottingham,University of Nottingham,Data Engineering,Master,2.0,34000,61.2,800,485,800,0.79

In [8]:
df.sample(5)

,Country,City,University,Program,Level,Duration_Years,Tuition_USD,Living_Cost_Index,Rent_USD,Visa_Fee_USD,Insurance_USD,Exchange_Rate
833,Ukraine,Odesa,Odesa Polytechnic,Artificial Intelligence,PhD,4.0,3600,41.8,320,120,300,36.80
782,Panama,David,ISAE University,Data Analytics,Bachelor,4.0,6800,47.5,450,100,400,1.00
725,Luxembourg,Bertrange,Chamber of Commerce School,Business Analytics,Master,2.0,400,75.4,1050,100,800,0.92
870,USA,MIT,Massachusetts,Robotics,PhD,5.0,56000,82.1,2100,160,1500,1.00
881,France,Bordeaux,University of Bordeaux,Information Systems,PhD,4.0,4300,72.1,1000,99,850,0.92